### ISSUE TITLE
Not work with LiveScript 1.3.1 and node v.0.12.7

### ISSUE THREAD

**Issue by DJFeu** [zbryikt/ptt-crawler#5]
$ lsc crawler.ls CodeJob
Failed at: crawler.ls
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/liohcl/pttcr/crawler.ls:3:11)
1| var fs, request, board, listCount, isSync, postList, postQueue, jar, cookie, postDone, fetchArticle, postListDone, fetchList, fetchIndex;
2| fs = require('fs');
3+ request = require('request');
4| if (process.argv.length < 3) {
5|   console.log("usage: lsc crawler.ls [board-name] ");
6|   console.log("example: lsc crawler.ls food");
7|   process.exit();
    at Module._compile (module.js:460:26)
    at Object.LiveScript.run (/usr/local/lib/node_modules/LiveScript/lib/node.js:22:19)
    at compileScript (/usr/local/lib/node_modules/LiveScript/lib/command.js:180:29)
    at /usr/local/lib/node_modules/LiveScript/lib/command.js:108:9
    at /usr/local/lib/node_modules/LiveScript/lib/command.js:98:5
